---
- name: Create temporary file for awx operator manifest
  ansible.builtin.tempfile:
    state: file
    suffix: awx
  register: awx_operator_tempfile

- name: Download awx operator manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ansible/awx-operator/{{ awx_operator_version }}/deploy/awx-operator.yaml"   # yamllint disable-line rule:line-length
    dest: "{{ awx_operator_tempfile.path }}"
    mode: '0664'

- name: create awx namespace
  kubernetes.core.k8s:
    name: "{{ awx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install awx operator
  kubernetes.core.k8s:
    state: present
    src: "{{ awx_operator_tempfile.path }}"
    namespace: "{{ awx_namespace }}"

- name: Create awx instance
  kubernetes.core.k8s:
    state: present
    template: awx.yml.j2
...
