---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
    update_cache: true
    cache_valid_time: "{{ awx_cache_valid_time }}"
  tags:
    - awx
    - awx.dependencies

- name: Install ansible dependencies
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
      - pyyaml
  tags:
    - awx
    - awx.dependencies

- name: Create dir for awx operator repo
  ansible.builtin.file:
    path: "{{ awx_operator_src_dir }}"
    state: directory
    owner: "{{ awx_kubectl_user }}"
    group: "{{ awx_kubectl_user }}"
    mode: '0755'
  become: true
  tags:
    - awx
    - awx.operator

- name: Clone awx operator repo
  ansible.builtin.git:
    repo: "{{ awx_operator_git_repo }}"
    dest: "{{ awx_operator_src_dir }}"
    version: "{{ awx_operator_version }}"
    force: true
  become: true
  become_user: "{{ awx_kubectl_user }}"
  tags:
    - awx
    - awx.operator
    - molecule-idempotence-notest

- name: create awx namespace
  kubernetes.core.k8s:
    name: "{{ awx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  tags:
    - awx
    - awx.instance
    - awx.operator

- name: Install awx operator
  ansible.builtin.command:
    cmd: make deploy
  args:
    chdir: "{{ awx_operator_src_dir }}"
  environment:
    NAMESPACE: "{{ awx_namespace }}"
  become: true
  become_user: "{{ awx_kubectl_user }}"
  register: operator_install
  changed_when: "'created' in operator_install.stdout"
  tags:
    - awx
    - awx.operator
    - molecule-idempotence-notest

- name: Deploy CRDs
  kubernetes.core.k8s:
    state: present
    definition: "{{ awx_crd }}"
    namespace: "{{ awx_namespace }}"
  when: awx_crd is defined
  tags:
    - awx
    - awx.crd
...
