---
- name: Verify
  hosts: awx-test-control-plane
  connection: docker
  gather_facts: false
  tasks:
    - name: Check executor dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      check_mode: true
      register: awx_verify
      failed_when: awx_verify.changed

    - name: Check ansible dependencies
      ansible.builtin.pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
      check_mode: true
      register: awx_verify
      failed_when: awx_verify.changed

    - name: Check awx namespace
      kubernetes.core.k8s:
        name: "awx"
        api_version: v1
        kind: Namespace
        state: present
      check_mode: true
      register: awx_verify
      failed_when: awx_verify.changed
...
